version: "3.6"
services:
  servicego:
    build: ./server-rest-api
    networks:
      - mongo-go
      - nginx-go
    ports: 
      - 3000:3000
    depends_on:
      - mongodb
  
  nginx:
    build: ./nginx-http2
    networks:
      - nginx-go
    depends_on:
      - servicego
    ports:
      - 8000:80
      - 8001:443
    command: [nginx-debug, '-g', 'daemon off;']
  mongodb:
    image: mongo:3.6-jessie
    command: --smallfiles
    networks:
      - mongo-go
    ports:
            - 27017:27017
            - 28017:28017
networks:
  mongo-go:
  nginx-go:
volumes:
  mongodb-data:
