version: "3.6"
services:
  servicego:
    image: falconr/user-microservice
    networks:
      - mongo-go
      - nginx-go
    ports: 
      - 8080:8080
    depends_on:
      - mongodb
    deploy:
      replicas: 3
      update_config:
       delay: 10s
      restart_policy:
        condition: on-failure
  nginx:
    image: falconr/nginx-http2
    networks:
      - nginx-go
    depends_on:
      - servicego
    ports:
      - 8000:80
      - 8001:443
    command: [nginx-debug, '-g', 'daemon off;']
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  mongodb:
    image: mongo:3.6-jessie
    command: --smallfiles
    networks:
      - mongo-go
    volumes:
      - "mongodb-data:/data"
    ports:
            - 27017:27017
            - 28017:28017
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8002:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mongo-go
      - nginx-go
networks:
  mongo-go:
  nginx-go:
volumes:
  mongodb-data:
    driver: local
