apiVersion: apps/v1
kind: Deployment
metadata:
    name: servicego

spec:
 replicas: 2
 selector:
  matchLabels:
   app: servicego
 template:
  metadata:
   labels:
    app: servicego
  spec:
   containers:
   - name: servicego
     image: falconr/user-microservice:latest



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: falconr/nginx-http2


---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: mangodb 
spec:
 replicas: 1
 selector:
  matchLabels:
   app: mongodb
 template:
   metadata:
    labels:
     app: mongodb
   spec:
    containers:
    - name: mongodb
      image: mongo:3.6-jessie
     # we want to persist the database storage on the disk by mounting the /data/db file on our local disk 
      volumeMounts:
          - mountPath: /data/db
            name: mongodb-persistent-storage
      #we want to store the data locally on the host machine 
    volumes:
        - name: mongodb-persistent-storage
          hostPath:
              path: /mnt/some/directory/structure  # where we want to store the data on our machine. This directory must have been created before.  
              type: DirectoryOrCreate
        #volumes: # the volume describtion on our local disk 
        # - name: mongodb-persistent-storage
    # pointing on the describtion of the volume 
    #persistentVolumeClaim:
    #    claimName: mongo-pv



